# Generated by Django 2.2.1 on 2019-06-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(help_text='Ingresar el NOMBRE para el legajo del alumno', max_length=120)),
                ('apellidos', models.CharField(help_text='Ingresar el APELLIDO para el legajo del alumno', max_length=120)),
                ('documento', models.IntegerField(help_text='Ingresar el DOCUMENTO para el legajo del alumno')),
                ('cuit', models.CharField(help_text='Ingresar el CUIT para el legajo del alumno', max_length=13)),
                ('fecha_nacimiento', models.DateField(help_text='Ingresar la FECHA DE NAC para el legajo del alumno')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo_area_telefono', models.CharField(max_length=15)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=120)),
                ('barrio', models.CharField(max_length=120)),
                ('numero', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinidelr.Persona')),
            ],
        ),
    ]
