# Generated by Django 2.2.1 on 2019-06-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinidedev', '0002_auto_20190603_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
